#%RAML 1.0
version: v1
title: sf-product-sys

uses:
  Common-Types: sf-common-types.raml

/products:
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            items: Common-Types.Product
            example:
              [
                {
                  "productId": "PROD1",
                  "name" : "Product 1",
                  "price": 100
                },
                {
                  "productId": "PROD2",
                  "name": "Product 2",
                  "price": 200
                }
              ]

  /{productId}:
    get:
      responses:
        200:
          body:
            application/json:
              type: Common-Types.Product
              example:
                 {
                  "productId": "PROD1",
                  "name" : "Product 1",
                  "price": 100
                }

  post:
    body:
      application/json:
        type: Common-Types.Product
        example:
          {
             "productId": "PROD1",
              "name" : "Product 1",
              "price": 100
          }